[project]
name = "fastapi-first-steps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydantic>=2.11.3",
    "pytest>=8.3.5",
    "sqlalchemy>=2.0.40",
]
